### ISSUE TITLE
Enhancement: Possibility format rss data

### ISSUE THREAD

**Issue by joaopedroo5** [Axobot-org/Axobot#110]
Hello, im trying to have a github releases notification channel in my discord.

Sadly, the data comes with little hiccups that I would like to remove, but as now there's no way to do it.

Eg: 
![image](https://github.com/user-attachments/assets/acf9ca07-a73f-4306-beba-08281e633c59)

Im asking for a tab in the dashboard to allow simple formatting, like regex replace.

**Comment by ZRunner** [comment]
Hi there!

After some research, it seems that GitHub RSS feed entries do not contain information about the summary type, so Axobot cannot remove the HTML tags. On the other hand, their content type is correctly described as `text/html`, so if you don't mind getting longer texts, you should probably use `{full_text}` instead of `{description}` in your template.

If this solution doesn't work for you,  I've also added your suggestion to our public [ideas list](https://discord.com/channels/356067272730607628/488769306524385301/1294645449034039376). Feel free to upvote it there!

If there are no further questions, could you please close this ticket? Thanks!
